### ISSUE TITLE
[Inquiry] Planners library

### ISSUE THREAD

**Issue by MFaisalZaki** [FragileTech/plangym#122]
Are there any plans to include a library from A*-based or MCTS planners inside the library?

**Comment by Guillemdb** [comment]
The main goal of `plangym` is to provide a set of environments  to test planning algorithms . I am currently writing a library of planning algorithms that I'll release over the next few months, but I'm trying to keep environments  and algorithms separate.

**Comment by MFaisalZaki** [comment]
That is great to hear. I am happy to assist with the library since I require it.

**Comment by MFaisalZaki** [comment]
@Guillemdb Can I ask what planners you are planning to implement. I am working now on iterated-width and MCTS.

**Comment by Guillemdb** [comment]
I am planning to focus in [these kind of algos](https://www.mdpi.com/2079-8954/11/2/105). It's something pretty niche, but it works a few orders of magnitude better than MCTS.

However, I still need a good reference implementation of MCTS, so if you know how to implement one I could give you a hand in taking care of setting up the project (packaging, docs, tests, etc.)

**Comment by MFaisalZaki** [comment]
I don’t mind sharing my MCTS, but I am still struggling to get it to search for plans. I need to search for a proper default policy and child selection.

**Comment by MFaisalZaki** [comment]
Hi @Guillemdb, I am trying to implement the `Arvandherd` planner based on a Monte Carlo Random Walk. Here is my implementation, and I would like your help since I failed to extract a plan when the search ended. Also, if you have any suggestions for improving it, that would be great.

The planner is aimed to work with [pddlgym](https://github.com/tomsilver/pddlgym). 

```
import math
import random
import sys
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Tuple
from copy import deepcopy

from tqdm import tqdm
from pddlgym.core import get_successor_states
from pddlgym.structs import Literal, LiteralConjunction
from pddlgym.prolog_interface import PrologInterface

def check_goal(state, goal):
	if isinstance(goal, Literal):
		if goal.is_negative and goal.positive in state.literals:
			return False
		if not goal.is_negative and goal not in state.literals:
			return False
		return True
	if isinstance(goal, LiteralConjunction):
		return all(check_goal(state, lit) for lit in goal.literals)
	prolog_interface = PrologInterface(state.literals, goal,
		max_assignment_count=2,
		allow_redundant_variables=True)
	assignments = prolog_interface.run()
	return len(assignments) > 0

def heuristics_goal_count(state, goal):
	# The simplest heuristic is to return how many goal predicates are acheived in this state.
	return len(goal.literals) - [p in state.literals for p in goal.literals].count(True)

def is_dead_state(state, env):
	return False

class MCRW:
	def __init__(self, env, hfn):
		self.env = env
		self.init_state, _ = self.env.reset()
		self.goal = self.init_state.goal
		self.hfn = hfn
		self.MAX_STEPS = 1000
		self.NUM_WALK = 100
		self.LENGTH_WALK = 100
	
	def search(self):
		s = deepcopy(self.init_state)
		hmin = self.hfn(s, self.goal)
		counter = 0
		while not check_goal(s, self.goal):
			if counter > self.MAX_STEPS or is_dead_state(s, self.env):
				s = deepcopy(self.init_state)
				counter = 0
			s = self.__walk__(s)
			h_value = self.hfn(s, self.goal)
			if h_value < hmin:
				hmin = h_value
				counter = 0
			else:
				counter += 1
		pass

	def __walk__(self, state):
		h_min = sys.maxsize
		s_min = None
		selected_actions = []
		for i in range(self.NUM_WALK):
			s_prime = deepcopy(state)
			for j in range(self.LENGTH_WALK):
				possible_actions = list(self.env.env.action_space.all_ground_literals(s_prime))
				if len(possible_actions) == 0: break
				selected_action = random.choice(possible_actions)
				s_prime = list(get_successor_states(s_prime, selected_action, self.env.env.domain)).pop()
				if check_goal(s_prime, self.goal): 
					return s_prime
			h_value = self.hfn(s_prime, self.goal)
			if h_value < h_min:
				h_min = h_value
				s_min = s_prime
		return state if s_min is None else s_min
```

**Comment by Guillemdb** [comment]
I tried to understand what you are trying to do, but it is too different to the plangym API. Unfortunately, now I don't have time to learn a new language/DSL.

Please let me know if you have any `plangym`-related questions.
